name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:      
      - uses:  actions/checkout@v4
        with: 
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: i dependencies
        run: npm ci
        env:
          NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL  }}

      - name: Generate statics files
        run: npm run generate
